config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"
  resources :users do
    resources :machines do
      collection do
        get 'vulcount'
      end
      member do
        get 'startscan'
        get 'viewresult'
        get 'downloadresult'
      end
    end
  end

  resources :sessions, only: [:new,:create,:destroy]
  match '/signout',to:'sessions#destroy',via:'delete'

  root :to => 'pages#home'
  match '/testcallback',to:'pages#testcallback',via:'get'
  match '/callback',to:'pages#callback',via:'get'
  match '/about',to:'pages#about',via:'get'
  match '/help',to:'pages#help',via:'get'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  enum status: [:waiting,:scanned,:scanning,:unknown]
  scope :need_scan, -> { where("status < 3") }

  belongs_to :user
  has_many :results
  validates :user_id, :presence => true
  validates :ip, :presence => true
  validates :status, :presence => true
  validates :ip, :uniqueness => true
  validates :ip, :format => { :with => Resolv::IPv4::Regex }
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :machine
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:member,:admin,:superadmin]
  default_scope -> { order('email DESC') }

  has_many :machines
  validates :name, :presence => true
  validates :role, :presence => true
  validates :name, :length => { :in => 2..50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, :presence => true
  validates :email, :format => { :with => VALID_EMAIL_REGEX }
  validates :email, uniqueness: { case_sensitive: false }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  include SessionsHelper
  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :signed_in_user,only: [:index]

  def index
    #@machines = current_user.machines.paginate(:page => params[:page], :per_page => 5)
    @machines = current_user.machines.need_scan.order("high DESC").paginate(:page => params[:page], :per_page => 5)
  end
  def vulcount
    @machines = Machine.all.order("high DESC").paginate(:page => params[:page], :per_page => 5)
    @LowCount=Result.where(threat:"Low").count()
    @HighCount=Result.where(threat:"High").count()
    @MidCount=Result.where(threat:"Medium").count()
    @chart = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 200, 60, 170]} )
      series = {
               :type=> 'pie',
               :name=> '漏洞数量',
               :data=> [
                  ['高危',  @HighCount],
                  ['中等',     @MidCount],
                  ['低危',    @LowCount]
               ]
      }
      f.series(series)
      f.options[:title][:text] = "漏洞数量概况"
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
      f.plot_options(:pie=>{
        :allowPointSelect=>true,
        :cursor=>"pointer" ,
        :dataLabels=>{
          :enabled=>true,
          :color=>"black",
          :style=>{
            :font=>"20px"
          }
        }
      })
    end
  end

  def show
    @machine = Machine.find(params[:id])
  end

  def startscan
    machine=Machine.find(params[:id])
    if machine.status == "scanning"
      flash[:info]=machine.ip+" already scanning"
    elsif machine.status == "unknown"
      flash[:info]=machine.ip+" can not scan this host"
    else
      machine.status = "scanning"
      machine.save!
      flash[:success]=machine.ip+" Start Scan OK"
      ScanWorker.perform_async(machine.ip)
    end
    redirect_to user_machines_path(current_user)
  end

  def viewresult
    machine=Machine.find(params[:id])
    @results=machine.results
  end

  def downloadresult
    machine=Machine.find(params[:id])
    puts machine.ip
    result_path = Rails.root.join('results','html',"#{ machine.ip }.html")
    send_file result_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if signed_in?
      redirect_to user_machines_path(current_user)
    end
  end
  def about
  end
  def dashboard
  end
  def testcallback
    user=User.find_by(email:"zengshan@ihep.ac.cn")
    if user
      sign_in user
      redirect_back_or user_machines_path(user)
    end
  end
  def callback
    data={
      client_id:ENV['APP_KEY'],
      client_secret:ENV['APP_SECRET'],
      grant_type:"authorization_code",
      redirect_uri:ENV['REDIRECT_URI'],
      code:params[:code]
    }
    res=Net::HTTP.post_form(URI.parse("https://login.ihep.ac.cn/oauth2/token"),data)
    body=res.body.gsub('\\','')
    body=body.gsub('"{','{')
    body=body.gsub('}"','}')
    body=JSON.parse(body)
    user = User.find_or_create_by(email:body["userInfo"]["cstnetId"].downcase)
    if user
      user.name=body["userInfo"]["truename"]
      user.save!
      sign_in user
      redirect_back_or user_machines_path(user)
    else
      flash.now[:error] = 'Invalid email'
      render 'home'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user
      sign_in user
      redirect_back_or user_machines_path(user)
    else
      flash.now[:error] = 'Invalid email'
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to 'https://login.ihep.ac.cn'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,only: [:show]
  before_action :correct_user,only:[:show]
  before_action :admin_user,only: [:index,:edit,:update]

  def index
    @users = User.paginate(page:params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success]= "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless (current_user.admin? or current_user.superadmin?)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = { value:remember_token,expires:3.weeks.from_now.utc }
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def is_admin?
    current_user.admin? || current_user.superadmin?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <hr>
  <footer>
    <div class="row">
      <center>
        <p>Copyright &copy; IHEP 2014</p>
      <center>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= t('safeihep') %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <% if signed_in? %>
        <li> <%= link_to t('dashboard'),user_machines_path(current_user),method:"get" %> </li>
        <% if is_admin? %>
          <li> <%= link_to t('admin_dashboard'),vulcount_user_machines_path(current_user),method:"get" %> </li>
        <% end %>
      <% end %>
        <li> <%= link_to t('help'),help_path %> </li>
    </ul>
    <% if signed_in? %>
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
         <a href="#" id="selected_language" class="dropdown-toggle" data-toggle="dropdown"> <%= (I18n.locale == :en)? t('english'): t('chinese') %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to t('english'), :controller => controller.controller_name,:action => controller.action_name, :locale => "en" %>
            </li>
            <li>
            <%= link_to t('chinese'), :controller => controller.controller_name,:action => controller.action_name, :locale => "zh-CN"%>
            </li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li> <%= link_to t('sign_out'),signout_path,method:"delete" %> </li>
          </ul>
        </li>
      </ul>
    <% else %>

    <% end %>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/machines/downloadresult.html.erb
<div class="container">
  <div class="panel panel-danger">
    <div class="panel-heading">Heading</div>
    <div class="panel-body">Panel Danger</div>
  </div>
</div>

app/views/machines/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <%= t('dashboard') %>
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <div class="panel-title"><%= t('scan_result') %></div>
        </div>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="col-md-1"><%= t('host') %></th>
                <th class="col-md-2"><%= t('high') %></th>
                <th class="col-md-2"><%= t('mid') %></th>
                <th class="col-md-2"><%= t('low') %></th>
                <th class="col-md-1"><%= t('status') %></th>
                <th class="col-md-4"><%= t('action') %></th>
              </tr>
            </thead>
            <tbody>
              <% @machines.each do |machine| %>
                <tr>
                  <td> <%= machine.ip %> </td>
                  <td> <%= machine.high %> </td>
                  <td> <%= machine.mid %> </td>
                  <td class="center"> <%= machine.low %> </td>
                  <td class="center">
                    <%= machine.status %>
                  </td>
                  <td class="center">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#scanModal<%= machine.id %>"><%= t('start_scan') %></button>
                    <!-- scanModal -->
                    <div class="modal fade" id="scanModal<%= machine.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                          </div>
                          <div class="modal-body">
                            <%= machine.ip %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <%= link_to("Confirm Scan",{:action =>'startscan', :id => machine.id},:class => 'btn btn-primary') %>
                          </div>
                        </div><!-- /.modal-content -->
                      </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                    <%= link_to(t('view_result'),{:action =>'viewresult', :id => machine.id},:class => 'btn btn-success') %>
                    <%= link_to(t('download_result'),{:action =>'downloadresult', :id => machine.id},:class => 'btn btn-info') %>

                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

      </div>
      <%= will_paginate @machines %>

    </div>
  </div>

</div>

app/views/machines/show.html.erb
<h1><%= @machine.ip %></h1>

app/views/machines/viewresult.html.erb
<div class="container">
  <% @results.each do |result| %>

    <% if result.threat != "Log" %>

      <% case result.threat when "High" %>
        <div class="panel panel-danger">
      <% when "Medium" %>
        <div class="panel panel-warning">
      <% when "Low" %>
        <div class="panel panel-info">
      <% end %>

        <div class="panel-heading"><%= result.threat %> <%= result.port %></div>
          <div class="panel-body">
            <%= simple_format(result.description) %> <br/>
            <% if result.xref !="NOXREF" %>
              <%= result.xref %>
            <% end %>
          </div>
        </div>
    <% end %>
  <% end %>
</div>

app/views/machines/vulcount.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 sidebar">
      <ul class="nav nav-sidebar">
      </ul>
    </div>
    <div class="col-md-10 main">
      <h1 class="page-header"><%= t('admin_dashboard') %></h1>
      <%= high_chart("my_id", @chart) %>
    </div>
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <div class="panel-title"><%= t('scan_result') %></div>
        </div>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="col-md-1"><%= t('host') %></th>
                <th class="col-md-2"><%= t('high') %></th>
                <th class="col-md-2"><%= t('mid') %></th>
                <th class="col-md-2"><%= t('low') %></th>
                <th class="col-md-1"><%= t('status') %></th>
                <th class="col-md-4"><%= t('action') %></th>
              </tr>
            </thead>
            <tbody>
              <% @machines.each do |machine| %>
                <tr>
                  <td> <%= machine.ip %> </td>
                  <td> <%= machine.high %> </td>
                  <td> <%= machine.mid %> </td>
                  <td class="center"> <%= machine.low %> </td>
                  <td class="center">
                    <%= machine.status %>
                  </td>
                  <td class="center">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#scanModal<%= machine.id %>"><%= t('start_scan') %></button>
                    <!-- scanModal -->
                    <div class="modal fade" id="scanModal<%= machine.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                          </div>
                          <div class="modal-body">
                            <%= machine.ip %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <%= link_to("Confirm Scan",{:action =>'startscan', :id => machine.id},:class => 'btn btn-primary') %>
                          </div>
                        </div><!-- /.modal-content -->
                      </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                    <%= link_to(t('view_result'),{:action =>'viewresult', :id => machine.id},:class => 'btn btn-success') %>
                    <%= link_to(t('download_result'),{:action =>'downloadresult', :id => machine.id},:class => 'btn btn-info') %>

                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

      </div>
      <%= will_paginate @machines %>

    </div>
  </div>
</div>

app/views/pages/help.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header"><%= t('help') %>
      </h1>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-12">

      <div class="panel-group" id="accordion">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                <%= t 'question1' %>
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <%= t 'answer1' %>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                <%= t 'question2' %>
              </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse in">
            <div class="panel-body">
                <%= t 'answer2' %>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                <%= t 'question3' %>
              </a>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse in">
            <div class="panel-body">
                <%= t 'answer3' %>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>
<!-- /.container -->

app/views/pages/home.html.erb
<% provide(:title,'Safe IHEP') %>
<div class="jumbotron">
    <center>
    <h1><%= t('safeihepplatform') %></h1>
      <p><%= t('seven_plus_twenty_four_hours') %></p>
      <p><a class="btn btn-primary btn-lg" href="https://login.ihep.ac.cn/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Fsafe.ihep.ac.cn%2Fcallback&client_id=57756&theme=full"><%= t('sign_in') %></a></p>
    </center>
</div>

<div class="section">

  <div class="container">

    <div class="row">
      <div class="col-lg-4 col-md-4">
        <h3><i class="fa fa-check-circle"></i> <%= t('use_and_admin_easy') %></h3>
        <p><%= t('use_and_admin_easy_more') %></p>
      </div>
      <div class="col-lg-4 col-md-4">
        <h3><i class="fa fa-pencil"></i> <%= t('max_protection') %></h3>
        <p><%= t('max_protection_more') %></p>
      </div>
      <div class="col-lg-4 col-md-4">
        <h3><i class="fa fa-folder-open"></i> <%= t('min_cost') %></h3>
        <p><%= t('min_cost_more') %></p>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

</div>
<!-- /.section -->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.email, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
              data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Dashboard
        <small>It's Nice to Meet You!</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="/">Home</a>
        </li>
        <li>Dashboard</li>
        <li class="active">All users</li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <div class="panel-title">All users</div>
        </div>
        <div class="panel-body">

          <%= will_paginate %>
            <ul class="users">
              <%= render @users %>
            </ul>
          <%= will_paginate %>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Dashboard
        <small>It's Nice to Meet You!</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="/">Home</a>
        </li>
        <li>Dashboard</li>
        <li class="active">Show users</li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <div class="panel-title">Show users</div>
        </div>
        <div class="panel-body">
          <%= form_for(@user) do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.text_field :email %>

          <% end %>

        </div>
      </div>
    </div>
  </div>

</div>